### ISSUE TITLE
Images for Online Resources

### ISSUE THREAD

**Issue by nlottig94** [nlottig94/EmilyDickinson6#2]
@ebeshero So we couldn't find the _Poems_, _Poems, Second Series_, and _Poems, Third Series_ in print from any of the Pitt libraries. We _did_ find an online .pdf of [_Poems, Second Series_](http://babel.hathitrust.org/cgi/pt?id=mdp.39015048699014;view=1up;seq=13) and [_Poems, Third Series_](http://babel.hathitrust.org/cgi/pt?id=coo.31924021990456;view=1up;seq=11) in the Pitt system, though, which is fine for the purposes that we need: images of the publications. However, we could _only_ find online text for [_Poems_](http://quod.lib.umich.edu/a/amverse/BAC5632.0001.001?rgn=main;view=fulltext). What should we do for the images of this? Is there a way we could obtain a copy of the book to scan the images in?

**Comment by ebeshero** [comment]
@nlottig94 @brookestewart I think I found your edition of Poems of 1891, edited by Higginson and Todd, with facsimile imaged pages, [archived on Hathi Trust](http://hdl.handle.net/2027/uc2.ark:/13960/t0sq8qz3w). Does that link work?

**Comment by ebeshero** [comment]
Oops...wait a sec. That's another copy of the Second Series...Let me try that again...

**Comment by nlottig94** [comment]
@ebeshero We already have that one. That's the Second Series. We're looking for the original first series.

**Comment by ebeshero** [comment]
Aha! I found a reprint of the first series, right here in the Greensburg campus library! 

Title:  Poems by Emily Dickinson / Edited by two of her friends Mabel Loomis Todd and T. W. Higginson.
Author: Dickinson, Emily, 1830-1886.
Contributors:   Todd, Mabel Loomis, 1856-1932, ed.
Higginson, Thomas Wentworth, 1823-1911, ed.
Publisher:  New York : Collectors Reprints, Inc., 1993.
Physical Description:   xii, [13]-152 p. ; 19 cm.
Notes:  Facsim. of: [1st ed.] Boston : Roberts Brothers, 1890. Reproduced from a copy in the Berg Collection, New York Public Library.
Two thousand five hundred copies published.
Location:   Greensburg Campus Library - Special Collections (Non-Circ)
Call Number:    PS1541 .P6 1993
Status: Not Checked Out

**Comment by ebeshero** [comment]
At least, I'm pretty sure it's the first series... 1890, right? It's hard to tell from the catalog entries.

**Comment by nlottig94** [comment]
Really??  I checked out all of the Emily Dickinson books from UPG! I didn't see it! But that looks right!!  I'll try to find it tomorrow!!  But since it's non-circulating, do I have to have special permissions to get it?

**Comment by ebeshero** [comment]
@nlottig94 @brookestewart You'd need to look at it in Special Collections, so ask one of the librarians for help. I think that means they put you in a study room with the book and you can look at it. I'm not 100% sure this is the edition you want (because the library catalog entries aren't giving me complete metadata, which is how I sent you to yet another second series before!) But this _looks_ right...Amanda Folk is a wiz with tracking down just the right edition in Hathi Trust, too--so definitely ask her and the librarians for help--I think we'll be able to track this down. I think if you can find a way to keep hunting _inside_ Hathi Trust, you might just find an electronic copy there. 

If this book at Greensburg campus _is_ the right edition, you'll probably be able to take photos of the pages yourself with a phone--but you'll need to learn the fine art of book imaging photography! It can be hard to hold a phone camera steady--so if you've got a real camera somewhere, you might want to use it!

**Comment by nlottig94** [comment]
Okay! I will go to the library either tomorrow or Monday to ask Amanda Folk about it. I know which poems I need to scan in, but I will have to make sure that I can do this. I will let you know what I find out! I will also bring my camera!

**Comment by nlottig94** [comment]
@ebeshero @brookestewart I just sent Amanda Folk an email with the book information and asking her how to go about looking at and scanning/imaging it.
