### ISSUE TITLE
New Web Space for Dickinson6?

### ISSUE THREAD

**Issue by nlottig94** [nlottig94/EmilyDickinson6#6]
@ebeshero Is there any way @brookestewart and I could get another web space for the Emily Dickinson: Fascicle 6 project???  I wanted to ask now before it's too late.  I feel like having both on one website will clutter the already full Emily Dickinson: Fascicle 16 site...

**Comment by ebeshero** [comment]
@nlottig94 Do you think there should be a directory _above_ dickinson16 that is just dickinson, and then you can build dickinson6 and/or other dickinson sites in directories within that space? Let's talk about this in the morning and I'll see what can be done.

**Comment by nlottig94** [comment]
@ebeshero I won't be in class today, but @brookestewart will talk to you about it this morning. That's sounds good to me.  That way we can almost make an archive for all of the Fascicles if we get that far in the future!

**Comment by ebeshero** [comment]
@nlottig94 @brookestewart If we do that, it will change all your site URLs in dickinson16, and we need to figure out how you'd like your address to be configured:

Literally we'd have:
`dickinson.newtfire.org/dickinson16/`
Instead of what you now have: 
`dickinson16.newtfire.org`.
But that seems a little long and repetitive, doesn't it? What do you think of renaming the fascicle directories by their number alone? That might look like:

`dickinson.newtfire.org/16/` and `dickinson.newtfire.org/6/`

We'd want to maybe leave the original `dickinson16` directory in place so we can set up a site redirect to your new homepage for both fascicle projects at `http://dickinson.newtfire.org`. Does this sound like a good plan?

**Comment by nlottig94** [comment]
@ebeshero I think this is a good plan.  What do you think @brookestewart?

**Comment by ebeshero** [comment]
I just rewrote the URLs above--I think the fascicle directories would be set at the end of the URL.

**Comment by nlottig94** [comment]
Which would then be followed by the page name in steps, correct?

**Comment by ebeshero** [comment]
@nlottig94 yes, in theory it would. In practice, the PSC people never returned an answer(!) So I'm worried that they won't get to this in time for your project presentation and submission this semester. Also my students in my Early American Lit class are supposed to be writing papers based on your Fascicle 16 project, so it's probably not a good idea to change the URL right now. It might be delayed because the PSC people are working on migrations to a new set of servers... Anyway, what's I'd suggest is that we just keep your site in dickinson16.newtfire.org, but maybe make the index page there be an index page for the WHOLE site which will contain multiple fascicles. And then create new directories for 16, 6, 10, and others, like:

```
dickinson16.newtfire.org/16/

dickinson16.newtfire.org/6/

dickinson16.newtfire.org/10/
```

Each of those can contain its own index page. Someday we'll be able to change the site URL, but in case we can't do it this week or next, I think we'll be okay with your rebuilding your site inside the current space. 
@brookestewart

**Comment by nlottig94** [comment]
@ebeshero That sounds good. We'll just hold off for the time being, and if we don't get an answer by next week, we'll just make what we have work!
