### ISSUE TITLE
Poem 14

### ISSUE THREAD

**Issue by nlottig94** [nlottig94/EmilyDickinson6#8]
@ebeshero @brookestewart @RJP43 
So I've begun coding [Poem 14](https://github.com/nlottig94/EmilyDickinson6/blob/master/Dickinson6_InitialXML/fs614.xml).  I'm noticing an issue though...the [Centenary Edition](https://github.com/nlottig94/EmilyDickinson6/blob/master/Web-Files/img/614/614cea.jpg) combines lines 2 and three, which really messes up line numbers...I was thinking that I could just put both of the line elements in a `app` and `rdg` tags, but it isn't valid with the TEI schema.  What do you suggest I do?
What you can see now is that I just added the extra part of ce's line 2 in an `rdg` at the end of the whole of line 2 and created an empty line for line 3, but since we output the line numbers on the html on the Dickinson16 site, I know that the lone numbers will not be correct for what the ce has..
Any suggestions??

**Comment by nlottig94** [comment]
@ebeshero @brookestewart @RJP43 
There is a similar issue with the [Centenary Edition](https://github.com/nlottig94/EmilyDickinson6/blob/master/Web-Files/img/608/608ce.jpg) of [Poem 8](https://github.com/nlottig94/EmilyDickinson6/blob/master/Dickinson6_InitialXML/fs608.xml).  Here lines 3 and 4 are being combined..

**Comment by ebeshero** [comment]
@nlottig94 @brookestewart As of last fall, the TEI Guidelines now permit `<rdg>` elements to contain `<l>` and `<lg>` elements--and it was a controversial decision but very popular with the TEI community for situations like the one you are facing. It _should, yes_ absolutely be valid to encode `<rdg>` elements to surround the `<l>` elements now: see:
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-rdg.html

**But!** you want to be very careful, because the XSLT you are using to output HTML, that calculates your line numbers is going to be affected: It probably won't work on these poems and you will need to amend it to generate the output you want. Or you will need to revisit the way you are encoding Dickinson's poems and outputting line numbers generally: it's opening the proverbial "can of worms," I know, but it's the sort of thing that professional coders and scholarly editors need to face with careful thought.

**Comment by ebeshero** [comment]
@nlottig94 @brookestewart If I understand the problem correctly, you have one edition that is putting two of Dickinson's lines together in just one line, and thus shortening her poem. One way to deal with that is to consider _what your line numbers_ in your HTML output are actually signalling. (And you will want to discuss this together and write it into your project methods page.)

Your current arrangement (I believe) outputs _every possible line_ in all the versions of a Dickinson poem you have located. That means that your line numbers on the HTML page will represent _as many lines as you have coded from each edition._ And typically that follows Dickinson's ms, but it _might not_ if one of the published editions actually adds lines. (I don't think we've seen that, have we?)

As long as you explain what the line numbers mean--that these represent the total _possible_ lines you've seen in _all_ the versions, maybe the following encoding strategy makes sense:
- Keep coding `<app>` and `<rdg>` elements only _inside_ the `<l>` elements as you've been doing--that's the old-fashioned way in TEI anyhow and not a bad way to proceed.
- If a poem has 14 total possible lines, and you see that one witness concatenates lines 13 and 14, you could then simply represent its line 13 as the full text of lines 13 and 14. But then you need a way to demonstrate that it does not represent line 14 at all, that it's line 14 is empty. Think about how you can do that.

**Comment by ebeshero** [comment]
@nlottig94 @brookestewart One thing you may want to experiment with is an alternative XSLT output from your HTML: to output separate editions of the poems, perhaps to arrange side-by-side on the screen. That could be an alternative layout to the one you configured with Alex last semester, and you could code it so that the line numbers are distinct for each separate edition. Something to think about.

**Comment by nlottig94** [comment]
@ebeshero Thanks!  @brookestewart and I will talk about it on Monday, well tomorrow.  I did try to surround `<l>` elements, and even `<lg>` elements in `<app>` and `<rdg>` tags, but it said it was invalid?  And, yes, I believe it would be easier to have separate tabs for Poem 12, and @RJP43 suggested that maybe Fascicle 10 will be our next Fascicle to code because there is another edition of Poem 12 in Fascicle 10. 
Could we talk to you about this tomorrow either before or after class?

**Comment by ebeshero** [comment]
@nlottig94 Yes, I'll try to come early before class--because I've got a faculty meeting at 11:45 tomorrow. In the meantime, I'd like to take a look at your schema lines and see why it's firing an error...It's supposed to be legal now. I wonder if you have a project schema rule that's blocking the encoding? (You might want that rule, actually, if you want to keep coding the original way...and then again, you might not!)

**Comment by nlottig94** [comment]
@ebeshero Thank you!  And I'm finished working with the Schematron now, so go for it! Just make sure you keep pulling in changes because I've been cropping pictures so you can't see my page markers and I've got all but three poems coded (8, 12, and 14).

**Comment by ebeshero** [comment]
Will do--after I try debugging some of Becca's code...more later! Thanks for the heads-up about pulling in changes! @nlottig94

**Comment by ebeshero** [comment]
@nlottig94 Okay! I'm looking at your files now: Do you have a particular XML you recommend that I work with? Otherwise I'll just pull randomly from something that isn't 8, 12, or 14.

**Comment by ebeshero** [comment]
@nlottig94 It's not your project schema...but I'm worried that it's a problem with the build of the TEI that was sent to `<oXygen>` so I've alerted my colleagues on the TEI Technical Council about it! For now, we'll have to encode the variants inside the lines, and do things very literally: So if one edition is lacking any content, you'll need to indicate that, I think with an empty `<rdg>` element. Will that work, even if it's a bit awkward? 

I am not sure what the problem is, since the TEI Guidelines clearly indicate you should be able to wrap `<lg>` in `<l>` elements inside `<app>` markup, but we'll just have to wait and see if this is resolved anytime soon. (sigh)

**Comment by ebeshero** [comment]
@nlottig94 @brookestewart If you'd like to follow the discussion of this in TEI Technical Council, see https://github.com/TEIC/TEI/issues/1322

**Comment by RJP43** [comment]
@ebeshero this is interesting convo. for the Nelson project as well because there are entire divs holding headlines and bodies of text that are only in the original articles and not in the other source text. We ended up just putting the app markup inside of the structural markup, but my initial wish was to surround the entire sections that are excluded. Check out our work around in this article: [1888-08-19](https://github.com/RJP43/CitySlaveGirls/blob/master/Nelson_CSG/CSG_XML/1888-08-19-ChTimes.xml)

**Comment by ebeshero** [comment]
@RJP43 @nlottig94 @brookestewart @spadafour
Aha! Problem solved! We all need to check and install updates to the TEI in oXygen: Follow these simple instructions and then you'll be able to wrap `<app><rdg>` elements around paragraphs, lines, and line-groups in TEI-All:
http://blogs.it.ox.ac.uk/jamesc/2014/04/02/auto-update-your-tei-framework-in-oxygen/

**Comment by nlottig94** [comment]
@ebeshero I'm updating it right now!  But I was thinking, that I really like your reasoning about how we could just use an empty `rdg` element for the second line that has been combined with the first and then specify that the numbers just represent how many lines are possible in each publication.  What do you think?
